#!/usr/bin/python3
"""
USB Device Model Generator for DEVFUZZ
Runs the extended stage2 LLVM pass on a USB driver's bitcode to extract
protocol constraints, then generates a USB model header file.

Usage:
  python3 generate_usb_model.py -b <driver.o.bc> -n <driver_name> -f <output.h>

Example:
  python3 generate_usb_model.py \
    -b analysis/linux/drivers/input/misc/ims-pcu.o.bc \
    -n ims_pcu \
    -f afl-proxy/aplib/usb/HWModel_ims_pcu_usb_model.h
"""

import subprocess
import os
import re
import argparse
from common import env_dir

def run_analysis(bc_file):
    """Run the stage2 LLVM pass and extract USB model code."""
    analysis_script = env_dir() + "/tools/shell_scripts/static-analysis.sh"
    tmpout = ".tmp.usb_pass_output"
    os.system(f"{analysis_script} {bc_file} >> {tmpout} 2>&1")

    with open(tmpout, "r") as f:
        output = f.read()
    os.remove(tmpout)
    return output

def parse_usb_model(output):
    """Parse the USB model section from the LLVM pass output."""
    # Extract between "USB Buffer Protocol Model" and "model->setUSBModel"
    usb_section = ""
    in_usb = False
    for line in output.splitlines():
        if "USB Buffer Protocol Model" in line:
            in_usb = True
            continue
        if "model->setUSBModel" in line:
            break
        if in_usb:
            usb_section += line + "\n"

    # Also extract constraint info from debug output
    constraints = []
    for line in output.splitlines():
        m = re.search(r"USB (?:switch )?constraint: buf\[(\d+)\] == (0x[\da-fA-F]+)", line)
        if m:
            offset = int(m.group(1))
            value = int(m.group(2), 16)
            constraints.append((offset, value))

    # Extract completion handlers
    handlers = []
    for line in output.splitlines():
        m = re.search(r"USB completion handler.*: (\w+)", line)
        if m:
            handlers.append(m.group(1))

    return usb_section, constraints, handlers

def generate_model_code(name, usb_model_code, constraints, handlers):
    """Generate the complete Stage2 model function with USB model."""
    code = f"""
// USB Protocol Model for {name}
// Auto-generated by generate_usb_model.py
// Completion handlers analyzed: {', '.join(handlers)}
// Constraints found: {len(constraints)}

Stage2HWModel * new_stage2_model_{name}() {{
  unordered_map<int, HWInput> mmio_mdl = {{}};
  vector<DMAInputModel> dma_mdl = {{}};
  auto * model = new Stage2HWModel("{name}", mmio_mdl, dma_mdl);

  // USB buffer protocol model (auto-extracted)
  {usb_model_code}
  model->setUSBModel(usb_mdl);

  return model;
}}
"""
    return code.strip()


def main():
    parser = argparse.ArgumentParser(description="Generate USB device model from LLVM bitcode")
    parser.add_argument('-b', '--bc', type=str, required=True,
                       help="LLVM bitcode file (.bc) for the USB driver")
    parser.add_argument('-n', '--name', type=str, required=True,
                       help="Name of the device/driver")
    parser.add_argument('-f', '--file', type=str, default=None,
                       help="Output file (default: print to stdout)")
    parser.add_argument('-v', '--verbose', action='store_true',
                       help="Print analysis details")
    args = parser.parse_args()

    print(f"Analyzing {args.bc} for USB protocol constraints...")
    output = run_analysis(args.bc)

    usb_model_code, constraints, handlers = parse_usb_model(output)

    if args.verbose:
        print(f"\nCompletion handlers: {handlers}")
        print(f"Constraints found: {len(constraints)}")
        for offset, value in sorted(constraints):
            print(f"  buf[{offset}] == 0x{value:x}")
        print(f"\nUSB model code:")
        print(usb_model_code)

    if not constraints:
        print("WARNING: No USB protocol constraints found.")
        print("The driver may not have USB completion handlers or buffer comparisons.")
        return

    model_code = generate_model_code(args.name, usb_model_code, constraints, handlers)

    if args.file:
        with open(args.file, 'a') as f:
            f.write("\n" + model_code + "\n")
        print(f"USB model appended to {args.file}")
    else:
        print(model_code)

    print(f"\nSummary: {len(constraints)} constraints from {len(handlers)} handlers")
    print("Offsets with constraints:", sorted(set(c[0] for c in constraints)))


if __name__ == "__main__":
    main()
